version: 2

build:
  tools:
    mkdocs: {}  # Diccionario vacío para MkDocs
  image: latest
  configuration: mkdocs.yml
  os: ubuntu-20.04
  python:
    version: 3.10.12
  formats: all
  output-dir: _build

mkdocs:
  version: 1.4.0

requirements:
  - mkdocs


