---
name: "🚀 Solicitud de Funcionalidad"
title: "[Feature Request]: "
about: descripcion
labels: 
  - feature-request

body:
  - type: markdown
    attributes:
      value: |
        **Descripción de la Funcionalidad**
        Describe claramente la funcionalidad que estás sugiriendo. ¿Qué problema resolvería? ¿Qué beneficios traería?

  - type: textarea
    attributes:
      label: Información Adicional
      placeholder: "Cualquier otra información relevante que desees agregar."


