---
name: "游 Solicitud de Funcionalidad"
title: "[Feature Request]: "
labels: 
  - feature-request

body:
  - type: markdown
    attributes:
      value: |
        **Descripci칩n de la Funcionalidad**
        Describe claramente la funcionalidad que est치s sugiriendo. 쯈u칠 problema resolver칤a? 쯈u칠 beneficios traer칤a?

  - type: markdown
    attributes:
      value: |
        **Propuesta de Implementaci칩n**
        Proporciona detalles sobre c칩mo esta funcionalidad podr칤a ser implementada. 쮿ay alg칰n enfoque o soluci칩n espec칤fica que sugieres?

  - type: markdown
    attributes:
      value: |
        **Caso de Uso**
        Proporciona un caso de uso o escenario en el que esta funcionalidad ser칤a 칰til o relevante.

  - type: markdown
    attributes:
      value: |
        **Capturas de Pantalla (si es aplicable)**
        Si tienes alguna idea visual sobre c칩mo deber칤a lucir esta funcionalidad, puedes adjuntar capturas de pantalla o bocetos aqu칤.

  - type: textarea
    attributes:
      label: Informaci칩n Adicional
      placeholder: Cualquier otra informaci칩n relevante que desees agregar.

